---
- name: Ensure firewall is installed
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Ensure firewalld is running and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: True

- name: Open required Wazuh ports 
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: True
    immediate: True
    state: enabled
  loop: "{{ wazuh_firewall_ports }}"

- name: Reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  changed_when: True
